<?php

Route::get(
    LaravelLocalization::transRoute('routes.simplePages.index'),
    'SimplePagesController@index'
)->name('simplePages');
Route::get(
    LaravelLocalization::transRoute('routes.simplePages.create'),
    'SimplePagesController@create'
)->name('simplePage.create');
Route::post(
    LaravelLocalization::transRoute('routes.simplePages.store'),
    'SimplePagesController@store'
)->name('simplePage.store');
Route::get(
    LaravelLocalization::transRoute('routes.simplePages.edit'),
    'SimplePagesController@edit'
)->name('simplePage.edit');
Route::put(
    LaravelLocalization::transRoute('routes.simplePages.update'),
    'SimplePagesController@update'
)->name('simplePage.update');
Route::delete(
    LaravelLocalization::transRoute('routes.simplePages.destroy'),
    'SimplePagesController@destroy'
)->name('simplePage.destroy');
