#!/bin/bash

# todo : customize the dependencies check

PackagesToCheck+=('php7.3')
PackagesToCheck+=('php7.3-cli')
PackagesToCheck+=('php7.3-fpm')
PackagesToCheck+=('php7.3-common')
PackagesToCheck+=('php7.3-json')
PackagesToCheck+=('php7.3-opcache')
PackagesToCheck+=('php7.3-mysql')
PackagesToCheck+=('php7.3-mbstring')
PackagesToCheck+=('php7.3-zip')
PackagesToCheck+=('php7.3-xml')
PackagesToCheck+=('php7.3-gd')
PackagesToCheck+=('php7.3-curl')
PackagesToCheck+=('php7.3-intl')
PackagesToCheck+=('php7.3-bcmath')
PackagesToCheck+=('php-redis')
PackagesToCheck+=('redis-server')
PackagesToCheck+=('mysql-server')
PackagesToCheck+=('nginx')
PackagesToCheck+=('git')
PackagesToCheck+=('supervisor')
PackagesToCheck+=('jpegoptim')
PackagesToCheck+=('optipng')
PackagesToCheck+=('pngquant')
PackagesToCheck+=('gifsicle')
PackagesToCheck+=('exif')
