#!/bin/bash

# todo : customize the dependencies check

PackagesToCheck+=('php7.4')
PackagesToCheck+=('php7.4-cli')
PackagesToCheck+=('php7.4-fpm')
PackagesToCheck+=('php7.4-common')
PackagesToCheck+=('php7.4-bcmath')
PackagesToCheck+=('php7.4-ctype')
PackagesToCheck+=('php7.4-json')
PackagesToCheck+=('php7.4-mbstring')
PackagesToCheck+=('php7.4-pdo')
PackagesToCheck+=('php7.4-tokenizer')
PackagesToCheck+=('php7.4-xml')
PackagesToCheck+=('php7.4-mysql')
PackagesToCheck+=('php7.4-opcache')
PackagesToCheck+=('php7.4-gd')
PackagesToCheck+=('php7.4-curl')
PackagesToCheck+=('php7.4-intl')
PackagesToCheck+=('php-redis')
PackagesToCheck+=('php-imagick')
PackagesToCheck+=('redis-server')
PackagesToCheck+=('imagemagick')
PackagesToCheck+=('mysql-server')
PackagesToCheck+=('nginx')
PackagesToCheck+=('git')
PackagesToCheck+=('supervisor')
PackagesToCheck+=('jpegoptim')
PackagesToCheck+=('optipng')
PackagesToCheck+=('pngquant')
PackagesToCheck+=('gifsicle')
PackagesToCheck+=('exif')
PackagesToCheck+=('ghostscript')
